version: "3"
services:
  db:
    image: postgres:16-alpine
    container_name: portal-aluno-db
    environment:
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: portal
      POSTGRES_DB: portal_db
    volumes:
      - portal-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  portal-db-data:
